version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.0.4
    - 32.1.1
    - 32.2.0
    - 32.3.0
    - 32.3.1
    - 32.3.2
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
